### ISSUE TITLE
'ascii' codec can't decode byte 0xc4 in position 1: ordinal not in range(128)

### ISSUE THREAD

**Issue by huseyint** [korayal/service.subtitles.planetdp#4]
Şöyle bir hata alıyorum ama fikri olan var mıdır?

> 18:39:54 392.073792 T:1321276400  NOTICE: Divxplanet: searching subtitles for The Walking Dead  6 16
> 18:39:54 392.129303 T:1321276400  NOTICE: Divxplanet: Finding dizi: The Walking Dead ()
> 18:39:56 394.253265 T:1321276400  NOTICE: Divxplanet: got media url http://altyazi.org/sub/m/26515/The-Walking-Dead.html
> 18:40:15 412.839935 T:1321276400  NOTICE: Divxplanet: found 8 subtitles
> 18:40:27 425.258270 T:1321276400  NOTICE: Divxplanet: o yoldayiz /sub/s/393462/The-Walking-Dead.html
> 18:40:27 425.266632 T:1321276400   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                              - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                             Error Type: <type 'exceptions.UnicodeDecodeError'>
>                                             Error Contents: 'ascii' codec can't decode byte 0xc4 in position 1: ordinal not in range(128)
>                                             Traceback (most recent call last):
>                                               File "/home/osmc/.kodi/addons/service.subtitles.divxplanet/service.py", line 360, in <module>
>                                                 subs = Download(params["link"],params["lang"], params["description"])
>                                               File "/home/osmc/.kodi/addons/service.subtitles.divxplanet/service.py", line 236, in Download
>                                                 shutil.rmtree(**temp**)
>                                               File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
>                                                 rmtree(fullname, ignore_errors, onerror)
>                                               File "/usr/lib/python2.7/shutil.py", line 241, in rmtree
>                                                 fullname = os.path.join(path, name)
>                                               File "/usr/lib/python2.7/posixpath.py", line 80, in join
>                                                 path += '/' + b
>                                             UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 1: ordinal not in range(128)
>                                             -->End of Python script error report<--
> 18:40:27 425.528625 T:1329665008   ERROR: GetDirectory - Error getting plugin://service.subtitles.divxplanet/?action=download&link=/sub/s/393462/The-Walking-Dead.html&lang=tr&description=The Walking Dead S06E16 Last Day on Earth.tr

**Comment by korayal** [comment]
Bahsi gecen sayfalara bakiyorum ama mevzubahis hataya sebep olan karaktere (Ä) ilgili sayfada  rastlamadim. Kullanmakta oldugunuz surumu ogrenebilir miyim? Bu aksam tekrar kontrol edeyim.

**Comment by huseyint** [comment]
0.0.12 versiyonunu kullanıyorum OSMC (raspberry pi 3) üzerinde. Daha fazla bilgi lazımsa gönderebilirim.

Bu arada her altyazı için bu hatayı veriyor, geçen hafta başka bir benzer konfigürasyonda sorunsuz çalıştığını görmüştüm, bu yeni kurulumda ne farklı bilemedim.

**Comment by korayal** [comment]
su an da ayni sorun devam ediyor mu? ben ayni bilgilerle sorgulayinca bir sorun goremiyorum. Cikan sonuc listesinde sondan 2. secenege tiklayarak sorunsuz indirebiliyorum.

Her altyazi icin bu hatayi veriyorsa sorunun kaynagi baska bir sey olabilir. Kodi'nin surumu nedir?

**Comment by huseyint** [comment]
Her alt yazı için oluyor, mesela şimdi başka bir tane denedim:

> 10:44:14 4126.555664 T:1345958896  NOTICE: Divxplanet: searching subtitles for Shameless (US)  6 12
> 10:44:14 4126.600586 T:1345958896  NOTICE: Divxplanet: Finding dizi: Shameless ()
> 10:44:16 4127.781250 T:1345958896  NOTICE: Divxplanet: got media url http://altyazi.org/sub/m/27711/Shameless.html
> 10:44:23 4135.286621 T:1345958896  NOTICE: Divxplanet: found 3 subtitles
> 10:44:28 4140.466797 T:1345958896  NOTICE: Divxplanet: o yoldayiz /sub/s/393492/Shameless.html
> 10:44:28 4140.506348 T:1345958896   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                              - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                             Error Type: <type 'exceptions.UnicodeDecodeError'>
>                                             Error Contents: 'ascii' codec can't decode byte 0xc4 in position 1: ordinal not in range(128)
>                                             Traceback (most recent call last):
>                                               File "/home/osmc/.kodi/addons/service.subtitles.divxplanet/service.py", line 360, in <module>
>                                                 subs = Download(params["link"],params["lang"], params["description"])
>                                               File "/home/osmc/.kodi/addons/service.subtitles.divxplanet/service.py", line 236, in Download
>                                                 shutil.rmtree(__temp__)
>                                               File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
>                                                 rmtree(fullname, ignore_errors, onerror)
>                                               File "/usr/lib/python2.7/shutil.py", line 241, in rmtree
>                                                 fullname = os.path.join(path, name)
>                                               File "/usr/lib/python2.7/posixpath.py", line 80, in join
>                                                 path += '/' + b
>                                             UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 1: ordinal not in range(128)
>                                             -->End of Python script error report<--
> 10:44:29 4140.712891 T:1354347504   ERROR: GetDirectory - Error getting plugin://service.subtitles.divxplanet/?action=download&link=/sub/s/393492/Shameless.html&lang=tr&description=Shameless (US) S06E12 Familia Supra Gallegorious Omnia!.tr

Kodi versiyonum 16.1-rc3, dün yüklendi sanırım bu daha önce 16.0 idi ama daha önce de çalışmıyordu.

**Comment by korayal** [comment]
Biraz gec oldu ama ancak vakit bulabildim. Birkac guncelleme yaptim. Oncelikle mevcut surumu kaldirip, asagidaki linkte bulunan zip dosyasini `Addons` bolumunden `Install from zip file` araciligi ile kurup test edebilir misiniz?

https://github.com/korayal/service.subtitles.divxplanet/archive/feature/migration-to-requests.zip

Bir sikinti olursa kurdugun OSMC surumunu de isteyecegim. Benzeri bir platformu yaratip tekrar deneyeyim bakalim :) Bu sorun en cok Raspberry Pi/Android kullanicilarinin basina geliyor sanirim.

**Comment by huseyint** [comment]
Teşekkürler, ilerleme var, bir kaç altyazıyı indirebildim ama bazılarında daha arama yaparken hata veriyor. Başarılı bir download örneği:

> 19:57:05 243441.593750 T:1304425456  NOTICE: [SEARCH !TVSHOW] Divxplanet: searching subtitles for Joy 2015
> 19:57:05 243441.609375 T:1304425456  NOTICE: getting media url
> 19:57:08 243443.906250 T:1304425456  NOTICE: Getting uri: http://www.altyazi.org/index.php?page=arama&arama=Joy
> 19:57:09 243444.875000 T:1304425456  NOTICE: Got uri [200]: http://altyazi.org/index.php?page=arama&arama=Joy
> 19:57:09 243445.343750 T:1304425456  NOTICE: 222Divxplanet: got media url /sub/m/53106/Joy.html
> 19:57:10 243446.156250 T:1304425456  NOTICE: Getting uri: http://www.altyazi.org/sub/m/53106/Joy.html
> 19:57:11 243447.109375 T:1304425456  NOTICE: Got uri [200]: http://altyazi.org/sub/m/53106/Joy.html
> 19:57:11 243447.265625 T:1304425456  NOTICE: Divxplanet: found a subtitle with description: Joy.2015.DVDSCR.700MB.ShAaNiG
> 19:57:11 243447.281250 T:1304425456  NOTICE: Divxplanet: found a subtitle with description: Joy.2015.1080p.WEB-DL.AAC2.0.H264-RARBG
> 19:57:11 243447.296875 T:1304425456  NOTICE: Previous line repeats 1 times.
> 19:57:11 243447.296875 T:1304425456  NOTICE: [SEARCH END]Divxplanet: found 3 subtitles
> 19:57:18 243454.250000 T:1304425456  NOTICE: Getting uri: http://www.altyazi.org/sub/s/393783/Joy.html
> 19:57:19 243455.093750 T:1304425456  NOTICE: Got uri [200]: http://altyazi.org/sub/s/393783/Joy.html
> 19:57:19 243455.390625 T:1304425456  NOTICE: Divxplanet: Subtitles saved to '/home/osmc/.kodi/userdata/addon_data/service.subtitles.divxplanet/temp/(393783)Joy_23.976fps_1CD_Turkce_SubRip_DiVXPlanet.rar'

Bunlar da fail olan örnekler:

> 19:52:46 243182.421875 T:1312814064  NOTICE: [SEARCH TVSHOW] Divxplanet: searching subtitles for Sherlock  3 3
> 19:52:46 243182.421875 T:1312814064  NOTICE: getting media url
> 19:52:47 243183.421875 T:1312814064  NOTICE: Getting uri: http://www.altyazi.org/index.php?page=arama&arama=Sherlock
> 19:52:48 243184.453125 T:1312814064  NOTICE: Got uri [200]: http://altyazi.org/index.php?page=arama&arama=Sherlock
> 19:52:49 243184.875000 T:1312814064   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                              - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                             Error Type: <type 'exceptions.ValueError'>
>                                             Error Contents: No valid results
>                                             Traceback (most recent call last):
>                                               File "/home/osmc/.kodi/addons/service.subtitles.divxplanet-feature-migration-to-requests/service.py", line 320, in <module>
>                                                 search(item)
>                                               File "/home/osmc/.kodi/addons/service.subtitles.divxplanet-feature-migration-to-requests/service.py", line 97, in search
>                                                 tvurl = get_media_url(["dizi", tvshow, year])
>                                               File "/home/osmc/.kodi/addons/service.subtitles.divxplanet-feature-migration-to-requests/service.py", line 84, in get_media_url
>                                                 raise ValueError('No valid results')
>                                             ValueError: No valid results
>                                             -->End of Python script error report<--
> 19:52:49 243185.093750 T:1352659952   ERROR: GetDirectory - Error getting plugin://service.subtitles.divxplanet/?action=search&languages=Turkish&preferredlanguage=English

ve

> 19:53:15 243211.468750 T:1329591280  NOTICE: [SEARCH TVSHOW] Divxplanet: searching subtitles for Modern Family  7 19
> 19:53:15 243211.468750 T:1329591280  NOTICE: getting media url
> 19:53:16 243212.468750 T:1329591280  NOTICE: Getting uri: http://www.altyazi.org/index.php?page=arama&arama=Modern+Family
> 19:53:17 243213.296875 T:1329591280  NOTICE: Got uri [200]: http://altyazi.org/index.php?page=arama&arama=Modern+Family
> 19:53:17 243213.593750 T:1329591280   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                              - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                             Error Type: <type 'exceptions.ValueError'>
>                                             Error Contents: No valid results
>                                             Traceback (most recent call last):
>                                               File "/home/osmc/.kodi/addons/service.subtitles.divxplanet-feature-migration-to-requests/service.py", line 320, in <module>
>                                                 search(item)
>                                               File "/home/osmc/.kodi/addons/service.subtitles.divxplanet-feature-migration-to-requests/service.py", line 97, in search
>                                                 tvurl = get_media_url(["dizi", tvshow, year])
>                                               File "/home/osmc/.kodi/addons/service.subtitles.divxplanet-feature-migration-to-requests/service.py", line 84, in get_media_url
>                                                 raise ValueError('No valid results')
>                                             ValueError: No valid results
>                                             -->End of Python script error report<--
> 19:53:18 243213.828125 T:1321202672   ERROR: GetDirectory - Error getting plugin://service.subtitles.divxplanet/?action=search&languages=Turkish&preferredlanguage=Unknown

**Comment by korayal** [comment]
ayni adresten guncel halini indirip tekrar deneyebilir misin? tasarimda degisiklige gidilmis sanirim :)

**Comment by huseyint** [comment]
Genel olarak çalışıyor gibi ama şu hatayı alıyorum yine Modern Family s07e19 için:

> 21:37:16 249451.796875 T:1369437168  NOTICE: [SEARCH TVSHOW] Divxplanet: searching subtitles for Modern Family  7 19
> 21:37:16 249451.796875 T:1369437168  NOTICE: getting media url
> 21:37:17 249453.000000 T:1369437168  NOTICE: Getting uri: http://www.altyazi.org/index.php?page=arama&arama=Modern+Family
> 21:37:18 249454.187500 T:1369437168  NOTICE: Got uri [200]: http://altyazi.org/index.php?page=arama&arama=Modern+Family
> 21:37:18 249454.484375 T:1369437168  NOTICE: Divxplanet: got media url /sub/m/22087/Modern-Family.html
> 21:37:18 249454.484375 T:1369437168  NOTICE: TV ID: Modern-Family
> 21:37:20 249455.890625 T:1369437168  NOTICE: Getting uri: http://www.altyazi.org/sub/m/22087/Modern-Family.html
> 21:37:24 249460.687500 T:1369437168  NOTICE: Got uri [200]: http://altyazi.org/sub/m/22087/Modern-Family.html
> 21:37:24 249460.750000 T:1369437168  NOTICE: Num links 770
> 21:37:28 249464.125000 T:1369437168   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                              - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                             Error Type: <type 'exceptions.UnicodeDecodeError'>
>                                             Error Contents: 'ascii' codec can't decode byte 0xe2 in position 32: ordinal not in range(128)
>                                             Traceback (most recent call last):
>                                               File "/home/osmc/.kodi/addons/service.subtitles.divxplanet-feature-migration-to-requests/service.py", line 324, in <module>
>                                                 search(item)
>                                               File "/home/osmc/.kodi/addons/service.subtitles.divxplanet-feature-migration-to-requests/service.py", line 151, in search
>                                                 filename
>                                             UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 32: ordinal not in range(128)
>                                             -->End of Python script error report<--
> 21:37:28 249464.453125 T:1400890352   ERROR: GetDirectory - Error getting plugin://service.subtitles.divxplanet/?action=search&languages=Turkish&preferredlanguage=Unknown

**Comment by korayal** [comment]
tekrar deneyelim :) olmamasi gereken bir yerden altyazi bulmus gibi gorunuyor.

**Comment by huseyint** [comment]
Bu sefer da aradığımdan çok alakasız sonuçlar geliyor :/ gerçi altyazi.org da aratınca da aynı yanlış sonuçlar geliyor:

> 00:07:52 186.635818 T:1292887024  NOTICE: [SEARCH !TVSHOW] Divxplanet: searching subtitles for Ich seh, Ich seh 2014
> 00:07:52 186.635941 T:1292887024  NOTICE: getting media url
> 00:07:53 187.641968 T:1292887024  NOTICE: Getting uri: http://www.altyazi.org/index.php?page=arama&arama=Ich+seh,+Ich+seh+2014
> 00:07:55 190.183121 T:1292887024  NOTICE: Got uri [200]: http://altyazi.org/index.php?page=arama&arama=Ich+seh,+Ich+seh+2014
> 00:07:56 190.526031 T:1292887024  NOTICE: 222Divxplanet: got media url /sub/m/40737/Winter-s-Tale.html
> 00:07:58 192.236053 T:1292887024  NOTICE: Getting uri: http://www.altyazi.org/sub/m/40737/Winter-s-Tale.html
> 00:08:00 194.659668 T:1292887024  NOTICE: Got uri [200]: http://altyazi.org/sub/m/40737/Winter-s-Tale.html
> 00:08:01 195.433838 T:1292887024  NOTICE: Divxplanet: found a subtitle with description: Winters.Tale.English.DL.DVDRiP.x264-ROOR | Winters.Tale.2014.DVDRip.x264-SPARKS
> 00:08:01 195.457825 T:1292887024  NOTICE: Previous line repeats 1 times.
> 00:08:01 195.457932 T:1292887024  NOTICE: Divxplanet: found a subtitle with description: Winters.Tale.2014.DVDRip.x264-SPARKS | EVO | MiLLENiUM | RARBG | ROOR
> 00:08:01 195.469269 T:1292887024  NOTICE: Divxplanet: found a subtitle with description: Winter's.Tale.2014.DVDRip - CPG | SPARKS | ROOR güncellendi.
> 00:08:01 195.481079 T:1292887024  NOTICE: Divxplanet: found a subtitle with description: WEBRİP-BİTO
> 00:08:01 195.492844 T:1292887024  NOTICE: Divxplanet: found a subtitle with description: BİTO
> 00:08:01 195.517197 T:1292887024  NOTICE: Previous line repeats 1 times.
> 00:08:01 195.517303 T:1292887024  NOTICE: Divxplanet: found a subtitle with description: Winter's.Tale.2014.1080p.WEBRip.x264.AAC-RARBG-30fps
> 00:08:01 195.529892 T:1292887024  NOTICE: Divxplanet: found a subtitle with description: Winters.Tale.2014.HDRip.X264.AC3-PLAYNOW
> 00:08:01 195.555435 T:1292887024  NOTICE: Previous line repeats 1 times.
> 00:08:01 195.555542 T:1292887024  NOTICE: Divxplanet: found a subtitle with description: Winters.Tale.2014.720p.BluRay.x264.YIFYWinters.Tale.2014.BRRiP.XVID.AC3-MAJESTICWinters.Tale.2014.720p.BluRay.x264-SPARKS | GanoolWinter's Tale (2014) 1080p BluRay DTS MultiSubs x264-NLU002
> 00:08:01 195.567719 T:1292887024  NOTICE: Divxplanet: found a subtitle with description: Winters.Tale.2014 | DVDRip | SPARKS | EVO | MiLLENiUM | RARBG | ROOR
> 00:08:01 195.579697 T:1292887024  NOTICE: Divxplanet: found a subtitle with description: Winters.Tale.2014 | Bluray - BRRip | Sparks | Tayto | DON | YIFY | Ganool | CHD | MAJESTIC |
> 00:08:01 195.580093 T:1292887024  NOTICE: [SEARCH END]Divxplanet: found 13 subtitles

ve

> 00:08:36 230.963898 T:1299182576  NOTICE: [SEARCH !TVSHOW] Divxplanet: searching subtitles for Joy 2015
> 00:08:36 230.964020 T:1299182576  NOTICE: getting media url
> 00:08:38 232.973831 T:1299182576  NOTICE: Getting uri: http://www.altyazi.org/index.php?page=arama&arama=Joy+2015
> 00:08:41 235.318878 T:1299182576  NOTICE: Got uri [200]: http://altyazi.org/index.php?page=arama&arama=Joy+2015
> 00:08:41 235.611954 T:1299182576  NOTICE: 222Divxplanet: got media url /sub/m/42084/In-The-Heart-Of-The-Sea.html
> 00:08:42 237.120972 T:1299182576  NOTICE: Getting uri: http://www.altyazi.org/sub/m/42084/In-The-Heart-Of-The-Sea.html
> 00:08:44 239.183960 T:1299182576  NOTICE: Got uri [200]: http://altyazi.org/sub/m/42084/In-The-Heart-Of-The-Sea.html
> 00:08:45 239.816299 T:1299182576  NOTICE: Divxplanet: found a subtitle with description: In.The.Heart.of.the.Sea.2015.DVDScr.XVID.AC3.HQ.Hive-CM8In.The.Heart.of.the.Sea.2015.576p.WEBRip.x264.AC3-OzZY1 | İyi seyirler.
> 00:08:45 239.830185 T:1299182576  NOTICE: Divxplanet: found a subtitle with description: In the Heart of the Sea 2015 BDRip x264-SPARKSIn.the.Heart.of.the.Sea.2015.1080p.BluRay.x264-SPARKSIn.the.Heart.of.the.Sea.2015.1080p.BluRay.H264.AAC-RARBGIn.the.Heart.of.the.Sea.2015.BRRip.XviD.AC3-RARBGIn.the.Heart.of.the.Sea.2015.1080p.BluRay.6CH.ShAaNiGIn.the.Heart.of.the.Sea.2015.BluRay.1080p.x264-Atmos.TrueHD7.1-MT
> 00:08:45 239.842499 T:1299182576  NOTICE: Divxplanet: found a subtitle with description: In.the.Heart.of.the.Sea.2015.720p.BluRay.x264-SPARKS
> 00:08:45 239.854385 T:1299182576  NOTICE: Divxplanet: found a subtitle with description: BluRay &gt;&gt;&gt; SPARKS | RARBG | ETRG | EVO | Ganool | RMTeam | ShAaNiG
> 00:08:45 239.854736 T:1299182576  NOTICE: [SEARCH END]Divxplanet: found 4 subtitles

**Comment by korayal** [comment]
Haklisin, aramayi iyilestirmek icin mevcut ise yil bilgisini de ekliyordum, fakat yil bilgisini parantez icerisinde eklemek daha etkili oluyor. Tekrar guncelledim.

**Comment by huseyint** [comment]
Selamlar tekrar, son hali ile Modern Family so7e18 için sorunsuz altyazı indirebiliyorum:

> 17:17:28 4985.095215 T:1680602096  NOTICE: [SEARCH TVSHOW] Divxplanet: searching subtitles for Modern Family  7 18
> 17:17:28 4985.095703 T:1680602096  NOTICE: getting media url
> 17:17:31 4987.202148 T:1680602096  NOTICE: Getting uri: http://www.altyazi.org/index.php?page=arama&arama=Modern+Family
> 17:17:35 4991.278809 T:1680602096  NOTICE: Got uri [200]: http://altyazi.org/index.php?page=arama&arama=Modern+Family
> 17:17:35 4991.576660 T:1680602096  NOTICE: Divxplanet: got media url /sub/m/22087/Modern-Family.html
> 17:17:35 4991.578125 T:1680602096  NOTICE: TV ID: Modern-Family
> 17:17:36 4993.085938 T:1680602096  NOTICE: Getting uri: http://www.altyazi.org/sub/m/22087/Modern-Family.html
> 17:17:43 4999.609375 T:1680602096  NOTICE: Got uri [200]: http://altyazi.org/sub/m/22087/Modern-Family.html
> 17:17:43 4999.672852 T:1680602096  NOTICE: Num links 774
> 17:17:48 5004.796875 T:1680602096  NOTICE: Divxplanet: found 6 subtitles
> 17:17:57 5014.114258 T:1680602096  NOTICE: Getting uri: http://www.altyazi.org/sub/s/393900/Modern-Family.html
> 17:18:05 5021.217285 T:1680602096  NOTICE: Got uri [200]: http://altyazi.org/sub/s/393900/Modern-Family.html
> 17:18:05 5022.065430 T:1680602096  NOTICE: Divxplanet: Subtitles saved to '/home/osmc/.kodi/userdata/addon_data/service.subtitles.divxplanet/temp/(393900)Modern_Family_23.976fps_1CD_Turkce_SubRip_DiVXPlanet.rar'

Ama Modern Family s07e19 için bugün çıkmış altyazıyı indirmek istediğimde daha arama yaparken hata geliyor, sonuç listelenmiyor:

> 17:21:56 5252.279785 T:1374680048  NOTICE: [SEARCH TVSHOW] Divxplanet: searching subtitles for Modern Family  7 19
> 17:21:56 5252.279785 T:1374680048  NOTICE: getting media url
> 17:21:56 5252.884766 T:1374680048  NOTICE: Getting uri: http://www.altyazi.org/index.php?page=arama&arama=Modern+Family
> 17:22:00 5256.779785 T:1374680048  NOTICE: Got uri [200]: http://altyazi.org/index.php?page=arama&arama=Modern+Family
> 17:22:00 5257.080566 T:1374680048  NOTICE: Divxplanet: got media url /sub/m/22087/Modern-Family.html
> 17:22:00 5257.082520 T:1374680048  NOTICE: TV ID: Modern-Family
> 17:22:02 5258.992188 T:1374680048  NOTICE: Getting uri: http://www.altyazi.org/sub/m/22087/Modern-Family.html
> 17:22:11 5267.432617 T:1374680048  NOTICE: Got uri [200]: http://altyazi.org/sub/m/22087/Modern-Family.html
> 17:22:11 5267.496582 T:1374680048  NOTICE: Num links 774
> 17:22:16 5272.541504 T:1374680048   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                              - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                             Error Type: <type 'exceptions.UnicodeDecodeError'>
>                                             Error Contents: 'ascii' codec can't decode byte 0xe2 in position 32: ordinal not in range(128)
>                                             Traceback (most recent call last):
>                                               File "/home/osmc/.kodi/addons/service.subtitles.divxplanet-feature-migration-to-requests/service.py", line 326, in <module>
>                                                 search(item)
>                                               File "/home/osmc/.kodi/addons/service.subtitles.divxplanet-feature-migration-to-requests/service.py", line 152, in search
>                                                 filename
>                                             UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 32: ordinal not in range(128)
>                                             -->End of Python script error report<--
> 17:22:16 5272.863770 T:1366291440   ERROR: GetDirectory - Error getting plugin://service.subtitles.divxplanet/?action=search&languages=Turkish&preferredlanguage=Unknown

Neden olabilir ki?

**Comment by korayal** [comment]
https://github.com/korayal/service.subtitles.divxplanet/archive/hotfix/i_hate_encoding_in_py2.zip adresinden tekrar bir deneme yapabilir misin?

Bu surumu gondermistim. Olmadiysa uzerine yenisini gondermeye calisayim. Dosya adlarinda bir gariplik var gibi gorunuyor.

**Comment by korayal** [comment]
Saniyorum bu sefer sorunun kaynagini buldum. hata kayitlarinda bahsi gecen `0xe2` karakteri `’` karakterine denk geliyor. Dosya adini olustururken muhtemelen bu bilgi dogru bir sekilde donusmuyor ve hata veriyor. bunun onune gececek duzenlemeyi ekledim. Sorun cozulduyse bir sonraki surum (0.1.1) ile birlikte duzelecektir.

**Comment by korayal** [comment]
Son halini suradan indirebilirsin:

https://github.com/korayal/service.subtitles.divxplanet/archive/master.zip

Yeni surumu 0.1.1 olarak gonderdim. Saniyorum hafta icerisinde yayina alirlar.
